/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

using System.Text.Json.Serialization;
using System.Collections.Generic;
using System.Text.Json;

namespace Google.GenAI.Types {
  /// <summary>
  /// Delivery mode for the generated content.
  /// </summary>

  [JsonConverter(typeof(DeliveryConverter))]
  public readonly record struct Delivery : IEquatable<Delivery> {
    public string Value { get; }

    private Delivery(string value) {
      Value = value;
    }

    /// <summary>
    /// Default value. This value is unused.
    /// </summary>
    public static Delivery DeliveryUnspecified { get; } = new("DELIVERY_UNSPECIFIED");

    /// <summary>
    /// Generated bytes are returned inline in the response.
    /// </summary>
    public static Delivery Inline { get; } = new("INLINE");

    /// <summary>
    /// Generated content is stored and a URI is returned.
    /// </summary>
    public static Delivery Uri { get; } = new("URI");

    public static IReadOnlyList<Delivery> AllValues {
      get;
    } = new[] { DeliveryUnspecified, Inline, Uri };

    public static Delivery FromString(string value) {
      if (string.IsNullOrEmpty(value)) {
        return new Delivery("DELIVERY_UNSPECIFIED");
      }

      foreach (var known in AllValues) {
        if (known.Value == value) {
          return known;
        }
      }

      return new Delivery(value);
    }

    public override string ToString() => Value ?? string.Empty;

    public static implicit operator Delivery(string value) => FromString(value);

    public bool Equals(Delivery other) => Value == other.Value;

    public override int GetHashCode() => Value?.GetHashCode() ?? 0;
  }

  public class DeliveryConverter : JsonConverter<Delivery> {
    public override Delivery Read(ref Utf8JsonReader reader, System.Type typeToConvert,
                                  JsonSerializerOptions options) {
      var value = reader.GetString();
      return Delivery.FromString(value);
    }

    public override void Write(Utf8JsonWriter writer, Delivery value,
                               JsonSerializerOptions options) {
      writer.WriteStringValue(value.Value);
    }
  }
}
